// Category data with predefined answers and point values (1-3)
// 1 = common/easy, 2 = moderate, 3 = niche/difficult

export const categories = {
  "Types of Fruit": [
    // Common (1 point)
    { answer: "Apple", points: 1 },
    { answer: "Banana", points: 1 },
    { answer: "Orange", points: 1 },
    { answer: "Grape", points: 1 },
    { answer: "Strawberry", points: 1 },
    { answer: "Watermelon", points: 1 },
    { answer: "Pineapple", points: 1 },
    { answer: "Lemon", points: 1 },
    { answer: "Lime", points: 1 },
    { answer: "Coconut", points: 1 },
    // Moderate (2 points)
    { answer: "Mango", points: 2 },
    { answer: "Peach", points: 2 },
    { answer: "Pear", points: 2 },
    { answer: "Cherry", points: 2 },
    { answer: "Blueberry", points: 2 },
    { answer: "Raspberry", points: 2 },
    { answer: "Kiwifruit", points: 2, aliases: ["Kiwi"] },
    { answer: "Plum", points: 2 },
    { answer: "Apricot", points: 2 },
    { answer: "Nectarine", points: 2 },
    { answer: "Blackberry", points: 2 },
    { answer: "Cranberry", points: 2 },
    { answer: "Grapefruit", points: 2 },
    { answer: "Tangerine", points: 2 },
    { answer: "Pomegranate", points: 2 },
    { answer: "Cantaloupe", points: 2 },
    { answer: "Honeydew", points: 2 },
    { answer: "Fig", points: 2 },
    { answer: "Date", points: 2 },
    { answer: "Guava", points: 2 },
    { answer: "Passionfruit", points: 2, aliases: ["Passion Fruit"] },
    { answer: "Clementine", points: 2 },
    { answer: "Avocado", points: 2 },
    { answer: "Papaya", points: 2 },
    { answer: "Plantain", points: 2 },
    { answer: "Blackcurrant", points: 2, aliases: ["Black Currant"] },
    { answer: "Goji Berry", points: 2, aliases: ["Goji"] },
    { answer: "Gooseberry", points: 2 },
    { answer: "Persimmon", points: 2 },
    // Niche (3 points)
    { answer: "Abiu", points: 3 },
    { answer: "Acai", points: 3, aliases: ["Acai Berry"] },
    { answer: "Acerola", points: 3 },
    { answer: "Ackee", points: 3 },
    { answer: "African Cherry Orange", points: 3 },
    { answer: "Akebi", points: 3 },
    { answer: "Aratiles", points: 3 },
    { answer: "Araza", points: 3 },
    { answer: "Bilberry", points: 3 },
    { answer: "Black Sapote", points: 3 },
    { answer: "Blood Orange", points: 3 },
    { answer: "Boysenberry", points: 3 },
    { answer: "Breadfruit", points: 3 },
    { answer: "Buddha's Hand", points: 3 },
    { answer: "Cactus Pear", points: 3, aliases: ["Prickly Pear"] },
    { answer: "Canistel", points: 3 },
    { answer: "Catmon", points: 3 },
    { answer: "Cempedak", points: 3 },
    { answer: "Cherimoya", points: 3 },
    { answer: "Citron", points: 3 },
    { answer: "Cloudberry", points: 3 },
    { answer: "Coco De Mer", points: 3 },
    { answer: "Crab Apple", points: 3, aliases: ["Crabapple"] },
    { answer: "Damson", points: 3 },
    { answer: "Dragon Fruit", points: 3, aliases: ["Dragonfruit", "Pitaya"] },
    { answer: "Durian", points: 3 },
    { answer: "Elderberry", points: 3 },
    { answer: "Feijoa", points: 3 },
    { answer: "Finger Lime", points: 3 },
    { answer: "Gac", points: 3 },
    { answer: "Galia Melon", points: 3 },
    { answer: "Grewia Asiatica", points: 3 },
    { answer: "Guarana", points: 3 },
    { answer: "Hala Fruit", points: 3 },
    { answer: "Honeyberry", points: 3 },
    { answer: "Huckleberry", points: 3 },
    { answer: "Jabuticaba", points: 3 },
    { answer: "Jackfruit", points: 3 },
    { answer: "Jambul", points: 3 },
    { answer: "Japanese Plum", points: 3 },
    { answer: "Jostaberry", points: 3 },
    { answer: "Jujube", points: 3 },
    { answer: "Juniper Berry", points: 3, aliases: ["Juniper"] },
    { answer: "Kaffir Lime", points: 3 },
    { answer: "Kiwano", points: 3 },
    { answer: "Kumquat", points: 3 },
    { answer: "Lanzones", points: 3 },
    { answer: "Loganberry", points: 3 },
    { answer: "Longan", points: 3 },
    { answer: "Loquat", points: 3 },
    { answer: "Lulo", points: 3 },
    { answer: "Lychee", points: 3, aliases: ["Litchi", "Lichi"] },
    { answer: "Macopa", points: 3 },
    { answer: "Magellan Barberry", points: 3 },
    { answer: "Mamey Apple", points: 3 },
    { answer: "Mamey Sapote", points: 3 },
    { answer: "Mangosteen", points: 3 },
    { answer: "Marionberry", points: 3 },
    { answer: "Medlar", points: 3 },
    { answer: "Miracle Fruit", points: 3 },
    { answer: "Monstera Deliciosa", points: 3 },
    { answer: "Mouse Melon", points: 3 },
    { answer: "Mulberry", points: 3 },
    { answer: "Muskmelon", points: 3 },
    { answer: "Nance", points: 3 },
    { answer: "Pawpaw", points: 3 },
    { answer: "Pineberry", points: 3 },
    { answer: "Plumcot", points: 3, aliases: ["Pluot"] },
    { answer: "Pomelo", points: 3 },
    { answer: "Quince", points: 3 },
    { answer: "Rambutan", points: 3 },
    { answer: "Redcurrant", points: 3, aliases: ["Red Currant"] },
    { answer: "Rose Apple", points: 3 },
    { answer: "Salak", points: 3 },
    { answer: "Salal Berry", points: 3, aliases: ["Salal"] },
    { answer: "Salmonberry", points: 3 },
    { answer: "Santol", points: 3 },
    { answer: "Sapodilla", points: 3 },
    { answer: "Sapote", points: 3 },
    { answer: "Sarguelas", points: 3 },
    { answer: "Saskatoon Berry", points: 3, aliases: ["Saskatoon"] },
    { answer: "Satsuma", points: 3 },
    { answer: "Sloe", points: 3 },
    { answer: "Soursop", points: 3 },
    { answer: "Star Apple", points: 3 },
    { answer: "Starfruit", points: 3, aliases: ["Star Fruit", "Carambola"] },
    { answer: "Sugar Apple", points: 3 },
    { answer: "Suriname Cherry", points: 3 },
    { answer: "Tamarillo", points: 3 },
    { answer: "Tamarind", points: 3 },
    { answer: "Tangelo", points: 3 },
    { answer: "Tayberry", points: 3 },
    { answer: "Thimbleberry", points: 3 },
    { answer: "Ugli Fruit", points: 3, aliases: ["Ugli"] },
    { answer: "White Currant", points: 3, aliases: ["Whitecurrant"] },
    { answer: "White Sapote", points: 3 },
    { answer: "Ximenia", points: 3 },
    { answer: "Yuzu", points: 3 }
  ],

  "Countries in Europe": [
    // Common (1 point)
    { answer: "France", points: 1 },
    { answer: "Germany", points: 1 },
    { answer: "Italy", points: 1 },
    { answer: "Spain", points: 1 },
    { answer: "United Kingdom", points: 1, aliases: ["UK", "England", "Britain", "Great Britain"] },
    { answer: "Russia", points: 1 },
    { answer: "Poland", points: 1 },
    { answer: "Ireland", points: 1 },
    // Moderate (2 points)
    { answer: "Greece", points: 2 },
    { answer: "Portugal", points: 2 },
    { answer: "Netherlands", points: 2, aliases: ["Holland", "The Netherlands"] },
    { answer: "Belgium", points: 2 },
    { answer: "Sweden", points: 2 },
    { answer: "Norway", points: 2 },
    { answer: "Austria", points: 2 },
    { answer: "Switzerland", points: 2 },
    { answer: "Denmark", points: 2 },
    { answer: "Finland", points: 2 },
    { answer: "Czech Republic", points: 2, aliases: ["Czechia"] },
    { answer: "Romania", points: 2 },
    { answer: "Hungary", points: 2 },
    { answer: "Croatia", points: 2 },
    { answer: "Ukraine", points: 2 },
    { answer: "Iceland", points: 2 },
    { answer: "Serbia", points: 2 },
    { answer: "Bulgaria", points: 2 },
    { answer: "Slovakia", points: 2 },
    { answer: "Turkey", points: 2 },
    // Niche (3 points)
    { answer: "Luxembourg", points: 3 },
    { answer: "Malta", points: 3 },
    { answer: "Slovenia", points: 3 },
    { answer: "Estonia", points: 3 },
    { answer: "Latvia", points: 3 },
    { answer: "Lithuania", points: 3 },
    { answer: "Montenegro", points: 3 },
    { answer: "Liechtenstein", points: 3 },
    { answer: "North Macedonia", points: 3, aliases: ["Macedonia"] },
    { answer: "Albania", points: 3 },
    { answer: "Bosnia and Herzegovina", points: 3, aliases: ["Bosnia"] },
    { answer: "Moldova", points: 3 },
    { answer: "Belarus", points: 3 },
    { answer: "Kosovo", points: 3 },
    { answer: "Andorra", points: 3 },
    { answer: "Monaco", points: 3 },
    { answer: "San Marino", points: 3 },
    { answer: "Vatican City", points: 3, aliases: ["The Vatican", "Vatican"] },
    { answer: "Cyprus", points: 3 },
    { answer: "Georgia", points: 3 },
    { answer: "Armenia", points: 3 },
    { answer: "Azerbaijan", points: 3 }
  ],

  "Animals": [
    // Common (1 point)
    { answer: "Dog", points: 1 },
    { answer: "Cat", points: 1 },
    { answer: "Lion", points: 1 },
    { answer: "Tiger", points: 1 },
    { answer: "Elephant", points: 1 },
    { answer: "Giraffe", points: 1 },
    { answer: "Zebra", points: 1 },
    { answer: "Bear", points: 1 },
    { answer: "Horse", points: 1 },
    { answer: "Cow", points: 1 },
    { answer: "Pig", points: 1 },
    { answer: "Chicken", points: 1 },
    { answer: "Rabbit", points: 1 },
    { answer: "Deer", points: 1 },
    { answer: "Monkey", points: 1 },
    { answer: "Fish", points: 1 },
    { answer: "Shark", points: 1 },
    { answer: "Snake", points: 1 },
    { answer: "Eagle", points: 1 },
    { answer: "Wolf", points: 1 },
    { answer: "Fox", points: 1 },
    { answer: "Duck", points: 1 },
    { answer: "Frog", points: 1 },
    { answer: "Mouse", points: 1 },
    // Moderate (2 points)
    { answer: "Penguin", points: 2 },
    { answer: "Kangaroo", points: 2 },
    { answer: "Koala", points: 2 },
    { answer: "Gorilla", points: 2 },
    { answer: "Chimpanzee", points: 2, aliases: ["Chimp"] },
    { answer: "Hippo", points: 2, aliases: ["Hippopotamus"] },
    { answer: "Rhinoceros", points: 2, aliases: ["Rhino"] },
    { answer: "Leopard", points: 2 },
    { answer: "Jaguar", points: 2 },
    { answer: "Cheetah", points: 2 },
    { answer: "Panda", points: 2 },
    { answer: "Dolphin", points: 2 },
    { answer: "Whale", points: 2 },
    { answer: "Octopus", points: 2 },
    { answer: "Crocodile", points: 2 },
    { answer: "Alligator", points: 2, aliases: ["Gator"] },
    { answer: "Turtle", points: 2 },
    { answer: "Parrot", points: 2 },
    { answer: "Owl", points: 2 },
    { answer: "Hawk", points: 2 },
    { answer: "Falcon", points: 2 },
    { answer: "Flamingo", points: 2 },
    { answer: "Camel", points: 2 },
    { answer: "Bison", points: 2 },
    { answer: "Moose", points: 2 },
    { answer: "Seal", points: 2 },
    { answer: "Otter", points: 2 },
    { answer: "Beaver", points: 2 },
    { answer: "Raccoon", points: 2 },
    { answer: "Hedgehog", points: 2 },
    { answer: "Bat", points: 2 },
    { answer: "Jellyfish", points: 2 },
    { answer: "Squid", points: 2 },
    { answer: "Crab", points: 2 },
    { answer: "Lobster", points: 2 },
    { answer: "Swan", points: 2 },
    { answer: "Pelican", points: 2 },
    { answer: "Toucan", points: 2 },
    { answer: "Peacock", points: 2 },
    { answer: "Ostrich", points: 2 },
    { answer: "Vulture", points: 2 },
    { answer: "Goat", points: 2 },
    { answer: "Sheep", points: 2 },
    { answer: "Donkey", points: 2 },
    { answer: "Turkey", points: 2 },
    { answer: "Goose", points: 2 },
    { answer: "Iguana", points: 2 },
    { answer: "Chameleon", points: 2 },
    { answer: "Salamander", points: 2 },
    { answer: "Seahorse", points: 2 },
    { answer: "Stingray", points: 2 },
    { answer: "Porcupine", points: 2 },
    { answer: "Wolverine", points: 2 },
    { answer: "Hyena", points: 2 },
    { answer: "Llama", points: 2 },
    { answer: "Alpaca", points: 2 },
    { answer: "Armadillo", points: 2 },
    { answer: "Starfish", points: 2 },
    // Niche (3 points)
    { answer: "Platypus", points: 3 },
    { answer: "Axolotl", points: 3 },
    { answer: "Quokka", points: 3 },
    { answer: "Capybara", points: 3 },
    { answer: "Pangolin", points: 3 },
    { answer: "Okapi", points: 3 },
    { answer: "Narwhal", points: 3 },
    { answer: "Manatee", points: 3 },
    { answer: "Tapir", points: 3 },
    { answer: "Aardvark", points: 3 },
    { answer: "Anteater", points: 3 },
    { answer: "Sloth", points: 3 },
    { answer: "Lemur", points: 3 },
    { answer: "Meerkat", points: 3 },
    { answer: "Wombat", points: 3 },
    { answer: "Chinchilla", points: 3 },
    { answer: "Ocelot", points: 3 },
    { answer: "Red Panda", points: 3, aliases: ["Lesser Panda"] },
    { answer: "Komodo Dragon", points: 3, aliases: ["Komodo"] },
    { answer: "Snow Leopard", points: 3 },
    { answer: "Caracal", points: 3 },
    { answer: "Serval", points: 3 },
    { answer: "Orangutan", points: 3, aliases: ["Orang-utan"] },
    { answer: "Gibbon", points: 3 },
    { answer: "Mandrill", points: 3 },
    { answer: "Badger", points: 3 }
  ],

  "Team Sports": [
    // Common (1 point)
    { answer: "Soccer", points: 1 },
    { answer: "Basketball", points: 1 },
    { answer: "Baseball", points: 1 },
    { answer: "Football", points: 1 },
    { answer: "Hockey", points: 1 },
    { answer: "Volleyball", points: 1 },
    // Moderate (2 points)
    { answer: "Rugby", points: 2 },
    { answer: "Cricket", points: 2 },
    { answer: "Lacrosse", points: 2 },
    { answer: "Softball", points: 2 },
    { answer: "Field Hockey", points: 2 },
    { answer: "Water Polo", points: 2 },
    { answer: "Handball", points: 2 },
    { answer: "Dodgeball", points: 2 },
    { answer: "Beach Volleyball", points: 2, aliases: ["Beach Volley"] },
    { answer: "Futsal", points: 2 },
    // Niche (3 points)
    { answer: "Curling", points: 3 },
    { answer: "Polo", points: 3 },
    { answer: "Ultimate Frisbee", points: 3, aliases: ["Ultimate"] },
    { answer: "Hurling", points: 3 },
    { answer: "Kickball", points: 3 },
    { answer: "Australian Rules Football", points: 3, aliases: ["Aussie Rules", "AFL", "Footy"] },
    { answer: "Gaelic Football", points: 3 },
    { answer: "Roller Derby", points: 3, aliases: ["Derby"] },
    { answer: "Netball", points: 3 },
    { answer: "Kabaddi", points: 3 },
    { answer: "Sepak Takraw", points: 3 },
    { answer: "Broomball", points: 3 },
    { answer: "Floorball", points: 3 }
  ],

  "US States": [
    // Common (1 point)
    { answer: "California", points: 1 },
    { answer: "Texas", points: 1 },
    { answer: "Florida", points: 1 },
    { answer: "New York", points: 1 },
    { answer: "Hawaii", points: 1 },
    { answer: "Alaska", points: 1 },
    // Moderate (2 points)
    { answer: "Pennsylvania", points: 2 },
    { answer: "Illinois", points: 2 },
    { answer: "Ohio", points: 2 },
    { answer: "Georgia", points: 2 },
    { answer: "North Carolina", points: 2 },
    { answer: "Michigan", points: 2 },
    { answer: "New Jersey", points: 2 },
    { answer: "Virginia", points: 2 },
    { answer: "Washington", points: 2 },
    { answer: "Arizona", points: 2 },
    { answer: "Massachusetts", points: 2 },
    { answer: "Tennessee", points: 2 },
    { answer: "Indiana", points: 2 },
    { answer: "Missouri", points: 2 },
    { answer: "Maryland", points: 2 },
    { answer: "Wisconsin", points: 2 },
    { answer: "Colorado", points: 2 },
    { answer: "Minnesota", points: 2 },
    { answer: "South Carolina", points: 2 },
    { answer: "Alabama", points: 2 },
    { answer: "Louisiana", points: 2 },
    { answer: "Kentucky", points: 2 },
    { answer: "Oregon", points: 2 },
    { answer: "Oklahoma", points: 2 },
    { answer: "Nevada", points: 2 },
    { answer: "Connecticut", points: 2 },
    // Niche (3 points)
    { answer: "Utah", points: 3 },
    { answer: "Iowa", points: 3 },
    { answer: "Arkansas", points: 3 },
    { answer: "Mississippi", points: 3 },
    { answer: "Kansas", points: 3 },
    { answer: "New Mexico", points: 3 },
    { answer: "Nebraska", points: 3 },
    { answer: "West Virginia", points: 3 },
    { answer: "Idaho", points: 3 },
    { answer: "New Hampshire", points: 3 },
    { answer: "Maine", points: 3 },
    { answer: "Montana", points: 3 },
    { answer: "Rhode Island", points: 3 },
    { answer: "Delaware", points: 3 },
    { answer: "South Dakota", points: 3 },
    { answer: "North Dakota", points: 3 },
    { answer: "Vermont", points: 3 },
    { answer: "Wyoming", points: 3 }
  ],

  "Pizza Toppings": [
    // Common (1 point)
    { answer: "Pepperoni", points: 1 },
    { answer: "Cheese", points: 1 },
    { answer: "Mushrooms", points: 1 },
    { answer: "Sausage", points: 1 },
    // Moderate (2 points)
    { answer: "Onions", points: 2 },
    { answer: "Peppers", points: 2, aliases: ["Bell Peppers", "Green Peppers"] },
    { answer: "Olives", points: 2 },
    { answer: "Bacon", points: 2 },
    { answer: "Ham", points: 2 },
    { answer: "Pineapple", points: 2 },
    { answer: "Tomatoes", points: 2 },
    { answer: "Spinach", points: 2 },
    { answer: "Chicken", points: 2 },
    { answer: "Jalapenos", points: 2, aliases: ["Jalapeno", "Jalapeño", "Jalapeños"] },
    { answer: "Garlic", points: 2 },
    { answer: "Ground Beef", points: 2 },
    { answer: "Basil", points: 2 },
    { answer: "Parmesan", points: 2 },
    // Niche (3 points)
    { answer: "Anchovies", points: 3 },
    { answer: "Artichoke", points: 3 },
    { answer: "Arugula", points: 3 },
    { answer: "Prosciutto", points: 3, aliases: ["Prosciutto di Parma"] },
    { answer: "Feta", points: 3 },
    { answer: "Goat Cheese", points: 3 },
    { answer: "Ricotta", points: 3 },
    { answer: "Gorgonzola", points: 3 },
    { answer: "Sun-dried Tomatoes", points: 3, aliases: ["Sundried Tomatoes", "Sun Dried Tomatoes"] },
    { answer: "Capers", points: 3 },
    { answer: "Salami", points: 3 },
    { answer: "Corn", points: 3 },
    { answer: "Eggplant", points: 3 },
    { answer: "Zucchini", points: 3 },
    { answer: "Broccoli", points: 3 },
    { answer: "Pesto", points: 3 },
    { answer: "Provolone", points: 3 },
    { answer: "Banana Peppers", points: 3 },
    { answer: "Pulled Pork", points: 3 },
    { answer: "Egg", points: 3 },
    { answer: "Fresh Mozzarella", points: 3, aliases: ["Fresh Mozz"] },
    { answer: "Roasted Red Peppers", points: 3 },
    { answer: "Chorizo", points: 3 },
    { answer: "Pancetta", points: 3 },
    { answer: "Shrimp", points: 3 }
  ],

  "Boy Names Starting with A": [
    { answer: "Aaron", points: 1 },
    { answer: "Adam", points: 1 },
    { answer: "Aiden", points: 1 },
    { answer: "Alex", points: 1 },
    { answer: "Alexander", points: 1 },
    { answer: "Andrew", points: 1 },
    { answer: "Anthony", points: 1 },
    { answer: "Austin", points: 1 },
    { answer: "Abraham", points: 2 },
    { answer: "Adrian", points: 2 },
    { answer: "Alan", points: 2 },
    { answer: "Albert", points: 2 },
    { answer: "Alec", points: 2 },
    { answer: "Alejandro", points: 2 },
    { answer: "Allen", points: 2 },
    { answer: "Amir", points: 2 },
    { answer: "Andre", points: 2 },
    { answer: "Andres", points: 2 },
    { answer: "Angel", points: 2 },
    { answer: "Antonio", points: 2 },
    { answer: "Arthur", points: 2 },
    { answer: "Asher", points: 2 },
    { answer: "Ashton", points: 2 },
    { answer: "August", points: 2 },
    { answer: "Avery", points: 2 },
    { answer: "Axel", points: 2 },
    { answer: "Abbott", points: 3 },
    { answer: "Abram", points: 3 },
    { answer: "Ace", points: 3 },
    { answer: "Adan", points: 3 },
    { answer: "Adriel", points: 3 },
    { answer: "Alaric", points: 3 },
    { answer: "Alberto", points: 3 },
    { answer: "Alden", points: 3 },
    { answer: "Aldo", points: 3 },
    { answer: "Alfie", points: 3 },
    { answer: "Alfonso", points: 3 },
    { answer: "Alfredo", points: 3 },
    { answer: "Alistair", points: 3 },
    { answer: "Alonso", points: 3 },
    { answer: "Alvaro", points: 3 },
    { answer: "Alvin", points: 3 },
    { answer: "Amari", points: 3 },
    { answer: "Ambrose", points: 3 },
    { answer: "Amos", points: 3 },
    { answer: "Anders", points: 3 },
    { answer: "Angelo", points: 3 },
    { answer: "Angus", points: 3 },
    { answer: "Ansel", points: 3 },
    { answer: "Anson", points: 3 },
    { answer: "Anton", points: 3 },
    { answer: "Apollo", points: 3 },
    { answer: "Archer", points: 3 },
    { answer: "Arden", points: 3 },
    { answer: "Ares", points: 3 },
    { answer: "Ari", points: 3 },
    { answer: "Ariel", points: 3 },
    { answer: "Arjun", points: 3 },
    { answer: "Arlo", points: 3 },
    { answer: "Armand", points: 3 },
    { answer: "Armando", points: 3 },
    { answer: "Arnold", points: 3 },
    { answer: "Arturo", points: 3 },
    { answer: "Asa", points: 3 },
    { answer: "Ashford", points: 3 },
    { answer: "Athen", points: 3 },
    { answer: "Atlas", points: 3 },
    { answer: "Atticus", points: 3 },
    { answer: "Augustin", points: 3 },
    { answer: "Augustine", points: 3 },
    { answer: "Avi", points: 3 },
    { answer: "Axl", points: 3 },
    { answer: "Axton", points: 3 },
    { answer: "Aziel", points: 3 }
  ],

  "Girl Names Starting with A": [
    { answer: "Abigail", points: 1 },
    { answer: "Alexis", points: 1 },
    { answer: "Allison", points: 1 },
    { answer: "Alyssa", points: 1 },
    { answer: "Amanda", points: 1 },
    { answer: "Amelia", points: 1 },
    { answer: "Amy", points: 1 },
    { answer: "Anna", points: 1 },
    { answer: "Ashley", points: 1 },
    { answer: "Audrey", points: 1 },
    { answer: "Ava", points: 1 },
    { answer: "Addison", points: 2 },
    { answer: "Adeline", points: 2 },
    { answer: "Adriana", points: 2 },
    { answer: "Alexa", points: 2 },
    { answer: "Alice", points: 2 },
    { answer: "Alicia", points: 2 },
    { answer: "Amber", points: 2 },
    { answer: "Andrea", points: 2 },
    { answer: "Angela", points: 2 },
    { answer: "Angelina", points: 2 },
    { answer: "Annie", points: 2 },
    { answer: "April", points: 2 },
    { answer: "Aria", points: 2 },
    { answer: "Ariana", points: 2 },
    { answer: "Ariel", points: 2 },
    { answer: "Aubrey", points: 2 },
    { answer: "Aurora", points: 2 },
    { answer: "Autumn", points: 2 },
    { answer: "Avery", points: 2 },
    { answer: "Abilene", points: 3 },
    { answer: "Abril", points: 3 },
    { answer: "Ada", points: 3 },
    { answer: "Adelaide", points: 3 },
    { answer: "Adele", points: 3 },
    { answer: "Adelina", points: 3 },
    { answer: "Adrienne", points: 3 },
    { answer: "Aileen", points: 3 },
    { answer: "Ainsley", points: 3 },
    { answer: "Alana", points: 3 },
    { answer: "Alayna", points: 3 },
    { answer: "Alena", points: 3 },
    { answer: "Alessandra", points: 3 },
    { answer: "Alina", points: 3 },
    { answer: "Aliyah", points: 3 },
    { answer: "Alma", points: 3 },
    { answer: "Alondra", points: 3 },
    { answer: "Althea", points: 3 },
    { answer: "Amara", points: 3 },
    { answer: "Amaya", points: 3 },
    { answer: "Amina", points: 3 },
    { answer: "Amira", points: 3 },
    { answer: "Anais", points: 3 },
    { answer: "Anastasia", points: 3 },
    { answer: "Angie", points: 3 },
    { answer: "Anika", points: 3 },
    { answer: "Anita", points: 3 },
    { answer: "Annalise", points: 3 },
    { answer: "Annette", points: 3 },
    { answer: "Annika", points: 3 },
    { answer: "Ansley", points: 3 },
    { answer: "Anya", points: 3 },
    { answer: "Arabella", points: 3 },
    { answer: "Arden", points: 3 },
    { answer: "Ariella", points: 3 },
    { answer: "Arlene", points: 3 },
    { answer: "Armani", points: 3 },
    { answer: "Aspen", points: 3 },
    { answer: "Astrid", points: 3 },
    { answer: "Athena", points: 3 },
    { answer: "Aurelia", points: 3 },
    { answer: "Avalon", points: 3 },
    { answer: "Averie", points: 3 },
    { answer: "Ayla", points: 3 },
    { answer: "Azalea", points: 3 },
    { answer: "Azariah", points: 3 }
  ],

  "Boy Names Starting with J": [
    { answer: "Jack", points: 1 },
    { answer: "Jacob", points: 1 },
    { answer: "Jake", points: 1 },
    { answer: "James", points: 1 },
    { answer: "Jason", points: 1 },
    { answer: "Jeremy", points: 1 },
    { answer: "John", points: 1 },
    { answer: "Jonathan", points: 1 },
    { answer: "Jordan", points: 1 },
    { answer: "Joseph", points: 1 },
    { answer: "Joshua", points: 1 },
    { answer: "Justin", points: 1 },
    { answer: "Jared", points: 2 },
    { answer: "Jax", points: 2 },
    { answer: "Jaxson", points: 2 },
    { answer: "Jay", points: 2 },
    { answer: "Jayden", points: 2 },
    { answer: "Jaylen", points: 2 },
    { answer: "Jeremiah", points: 2 },
    { answer: "Jerome", points: 2 },
    { answer: "Jerry", points: 2 },
    { answer: "Jesse", points: 2 },
    { answer: "Jimmy", points: 2 },
    { answer: "Joel", points: 2 },
    { answer: "Joey", points: 2 },
    { answer: "Johnny", points: 2 },
    { answer: "Jonah", points: 2 },
    { answer: "Jude", points: 2 },
    { answer: "Julian", points: 2 },
    { answer: "Jabari", points: 3 },
    { answer: "Jace", points: 3 },
    { answer: "Jacoby", points: 3 },
    { answer: "Jagger", points: 3 },
    { answer: "Jaiden", points: 3 },
    { answer: "Jairo", points: 3 },
    { answer: "Jalen", points: 3 },
    { answer: "Jamal", points: 3 },
    { answer: "Jamari", points: 3 },
    { answer: "Jameson", points: 3 },
    { answer: "Jamil", points: 3 },
    { answer: "Jamir", points: 3 },
    { answer: "Jarrett", points: 3 },
    { answer: "Jarvis", points: 3 },
    { answer: "Jasiah", points: 3 },
    { answer: "Jasper", points: 3 },
    { answer: "Javier", points: 3 },
    { answer: "Javon", points: 3 },
    { answer: "Jaxton", points: 3 },
    { answer: "Jayce", points: 3 },
    { answer: "Jayson", points: 3 },
    { answer: "Jedidiah", points: 3 },
    { answer: "Jeff", points: 2 },
    { answer: "Jefferson", points: 3 },
    { answer: "Jeffery", points: 3 },
    { answer: "Jensen", points: 3 },
    { answer: "Jenson", points: 3 },
    { answer: "Jericho", points: 3 },
    { answer: "Jermaine", points: 3 },
    { answer: "Jessie", points: 3 },
    { answer: "Jethro", points: 3 },
    { answer: "Jett", points: 3 },
    { answer: "Joaquim", points: 3 },
    { answer: "Joaquin", points: 3 },
    { answer: "Jonas", points: 3 },
    { answer: "Jordi", points: 3 },
    { answer: "Jordy", points: 3 },
    { answer: "Jorge", points: 3 },
    { answer: "Josiah", points: 3 },
    { answer: "Jovani", points: 3 },
    { answer: "Judah", points: 3 },
    { answer: "Judson", points: 3 },
    { answer: "Julien", points: 3 },
    { answer: "Julio", points: 3 },
    { answer: "Julius", points: 3 },
    { answer: "Junior", points: 3 }
  ],

  "Girl Names Starting with J": [
    { answer: "Jacqueline", points: 1 },
    { answer: "Jade", points: 1 },
    { answer: "Jamie", points: 1 },
    { answer: "Jane", points: 1 },
    { answer: "Jasmine", points: 1 },
    { answer: "Jenna", points: 1 },
    { answer: "Jennifer", points: 1 },
    { answer: "Jessica", points: 1 },
    { answer: "Jordan", points: 1 },
    { answer: "Joy", points: 1 },
    { answer: "Julia", points: 1 },
    { answer: "Julie", points: 1 },
    { answer: "Jackie", points: 2 },
    { answer: "Jada", points: 2 },
    { answer: "Janet", points: 2 },
    { answer: "Jean", points: 2 },
    { answer: "Jenny", points: 2 },
    { answer: "Jillian", points: 2 },
    { answer: "Joan", points: 2 },
    { answer: "Joanna", points: 2 },
    { answer: "Jocelyn", points: 2 },
    { answer: "Josephine", points: 2 },
    { answer: "Josie", points: 2 },
    { answer: "Joyce", points: 2 },
    { answer: "Judith", points: 2 },
    { answer: "Juliana", points: 2 },
    { answer: "Juliet", points: 2 },
    { answer: "June", points: 2 },
    { answer: "Justine", points: 2 },
    { answer: "Jacklyn", points: 3 },
    { answer: "Jaclyn", points: 3 },
    { answer: "Jaime", points: 3 },
    { answer: "Jaliyah", points: 3 },
    { answer: "Jana", points: 3 },
    { answer: "Janae", points: 3 },
    { answer: "Janelle", points: 3 },
    { answer: "Janessa", points: 3 },
    { answer: "Janine", points: 3 },
    { answer: "Janis", points: 3 },
    { answer: "Jayda", points: 3 },
    { answer: "Jayla", points: 3 },
    { answer: "Jaylah", points: 3 },
    { answer: "Jayleen", points: 3 },
    { answer: "Jaylin", points: 3 },
    { answer: "Jazlyn", points: 3 },
    { answer: "Jazmin", points: 3 },
    { answer: "Jeanine", points: 3 },
    { answer: "Jeannette", points: 3 },
    { answer: "Jemma", points: 3 },
    { answer: "Jessa", points: 3 },
    { answer: "Jessamine", points: 3 },
    { answer: "Jessie", points: 3 },
    { answer: "Jewel", points: 3 },
    { answer: "Jewell", points: 3 },
    { answer: "Jewels", points: 3 },
    { answer: "Jianna", points: 3 },
    { answer: "Jimena", points: 3 },
    { answer: "Joanie", points: 3 },
    { answer: "Jocelynn", points: 3 },
    { answer: "Jodi", points: 3 },
    { answer: "Joelle", points: 3 },
    { answer: "Johana", points: 3 },
    { answer: "Johanna", points: 3 },
    { answer: "Jolena", points: 3 },
    { answer: "Jolene", points: 3 },
    { answer: "Jolie", points: 3 },
    { answer: "Jolina", points: 3 },
    { answer: "Jordin", points: 3 },
    { answer: "Josefina", points: 3 },
    { answer: "Joslyn", points: 3 },
    { answer: "Journee", points: 3 },
    { answer: "Jovie", points: 3 },
    { answer: "Julianna", points: 3 },
    { answer: "Juliette", points: 3 },
    { answer: "Julissa", points: 3 },
    { answer: "Juniper", points: 3 }
  ],

  "Boy Names Starting with R": [
    { answer: "Randy", points: 1 },
    { answer: "Raymond", points: 1 },
    { answer: "Richard", points: 1 },
    { answer: "Robert", points: 1 },
    { answer: "Roger", points: 1 },
    { answer: "Ronald", points: 1 },
    { answer: "Roy", points: 1 },
    { answer: "Russell", points: 1 },
    { answer: "Ryan", points: 1 },
    { answer: "Rafael", points: 2 },
    { answer: "Ralph", points: 2 },
    { answer: "Ramon", points: 2 },
    { answer: "Raphael", points: 2 },
    { answer: "Reginald", points: 2 },
    { answer: "Ricardo", points: 2 },
    { answer: "Ricky", points: 2 },
    { answer: "Riley", points: 2 },
    { answer: "Robin", points: 2 },
    { answer: "Rodney", points: 2 },
    { answer: "Rodrigo", points: 2 },
    { answer: "Roman", points: 2 },
    { answer: "Ronnie", points: 2 },
    { answer: "Ross", points: 2 },
    { answer: "Ruben", points: 2 },
    { answer: "Raiden", points: 3 },
    { answer: "Raleigh", points: 3 },
    { answer: "Ramiro", points: 3 },
    { answer: "Randall", points: 3 },
    { answer: "Rashad", points: 3 },
    { answer: "Rashid", points: 3 },
    { answer: "Raul", points: 3 },
    { answer: "Ravi", points: 3 },
    { answer: "Ray", points: 3 },
    { answer: "Raylan", points: 3 },
    { answer: "Rayne", points: 3 },
    { answer: "Reed", points: 3 },
    { answer: "Reese", points: 3 },
    { answer: "Regan", points: 3 },
    { answer: "Reggie", points: 3 },
    { answer: "Reign", points: 3 },
    { answer: "Remington", points: 3 },
    { answer: "Remy", points: 3 },
    { answer: "Renato", points: 3 },
    { answer: "Reno", points: 3 },
    { answer: "Renzo", points: 3 },
    { answer: "Reuben", points: 3 },
    { answer: "Rex", points: 3 },
    { answer: "Rhett", points: 3 },
    { answer: "Rhys", points: 3 },
    { answer: "Ridge", points: 3 },
    { answer: "Ridley", points: 3 },
    { answer: "Rigby", points: 3 },
    { answer: "Riordan", points: 3 },
    { answer: "River", points: 3 },
    { answer: "Roberto", points: 3 },
    { answer: "Rocco", points: 3 },
    { answer: "Rocky", points: 3 },
    { answer: "Roderick", points: 3 },
    { answer: "Roland", points: 3 },
    { answer: "Rollins", points: 3 },
    { answer: "Rollo", points: 3 },
    { answer: "Rome", points: 3 },
    { answer: "Ronaldo", points: 3 },
    { answer: "Ronan", points: 3 },
    { answer: "Ronin", points: 3 },
    { answer: "Roper", points: 3 },
    { answer: "Roscoe", points: 3 },
    { answer: "Rowan", points: 3 },
    { answer: "Royce", points: 3 },
    { answer: "Rudolph", points: 3 },
    { answer: "Rudy", points: 3 },
    { answer: "Rufus", points: 3 },
    { answer: "Ryder", points: 3 },
    { answer: "Ryker", points: 3 },
    { answer: "Rylan", points: 3 }
  ],

  "Girl Names Starting with R": [
    { answer: "Rachel", points: 1 },
    { answer: "Rebecca", points: 1 },
    { answer: "Riley", points: 1 },
    { answer: "Rita", points: 1 },
    { answer: "Roberta", points: 1 },
    { answer: "Robin", points: 1 },
    { answer: "Rosa", points: 1 },
    { answer: "Rose", points: 1 },
    { answer: "Ruby", points: 1 },
    { answer: "Ruth", points: 1 },
    { answer: "Raquel", points: 2 },
    { answer: "Raven", points: 2 },
    { answer: "Reagan", points: 2 },
    { answer: "Reese", points: 2 },
    { answer: "Regina", points: 2 },
    { answer: "Renee", points: 2 },
    { answer: "Rhonda", points: 2 },
    { answer: "Robyn", points: 2 },
    { answer: "Rochelle", points: 2 },
    { answer: "Rosalie", points: 2 },
    { answer: "Rosemary", points: 2 },
    { answer: "Rosie", points: 2 },
    { answer: "Roxanne", points: 2 },
    { answer: "Rylee", points: 2 },
    { answer: "Rae", points: 3 },
    { answer: "Raelynn", points: 3 },
    { answer: "Rafaela", points: 3 },
    { answer: "Raina", points: 3 },
    { answer: "Ramona", points: 3 },
    { answer: "Ramya", points: 3 },
    { answer: "Randa", points: 3 },
    { answer: "Raya", points: 3 },
    { answer: "Raylee", points: 3 },
    { answer: "Rayna", points: 3 },
    { answer: "Reba", points: 3 },
    { answer: "Regan", points: 3 },
    { answer: "Reign", points: 3 },
    { answer: "Reina", points: 3 },
    { answer: "Remi", points: 3 },
    { answer: "Remy", points: 3 },
    { answer: "Renata", points: 3 },
    { answer: "Reyna", points: 3 },
    { answer: "Rhea", points: 3 },
    { answer: "Rhianna", points: 3 },
    { answer: "Rhiannon", points: 3 },
    { answer: "Rhoda", points: 3 },
    { answer: "Rhylee", points: 3 },
    { answer: "Richelle", points: 3 },
    { answer: "Rihanna", points: 3 },
    { answer: "Rina", points: 3 },
    { answer: "River", points: 3 },
    { answer: "Rivka", points: 3 },
    { answer: "Roisin", points: 3 },
    { answer: "Romelia", points: 3 },
    { answer: "Romilly", points: 3 },
    { answer: "Romina", points: 3 },
    { answer: "Romona", points: 3 },
    { answer: "Rory", points: 3 },
    { answer: "Rosabel", points: 3 },
    { answer: "Rosalind", points: 3 },
    { answer: "Rosalinda", points: 3 },
    { answer: "Rosaline", points: 3 },
    { answer: "Rosalyn", points: 3 },
    { answer: "Rosanna", points: 3 },
    { answer: "Rosario", points: 3 },
    { answer: "Roselyn", points: 3 },
    { answer: "Rosetta", points: 3 },
    { answer: "Rosina", points: 3 },
    { answer: "Roslyn", points: 3 },
    { answer: "Rowan", points: 3 },
    { answer: "Rowena", points: 3 },
    { answer: "Roxie", points: 3 },
    { answer: "Rue", points: 3 },
    { answer: "Ruthie", points: 3 },
    { answer: "Ryleigh", points: 3 },
    { answer: "Rylie", points: 3 }
  ],

  "Boy Names Starting with L": [
    { answer: "Larry", points: 1 },
    { answer: "Lawrence", points: 1 },
    { answer: "Lee", points: 1 },
    { answer: "Leo", points: 1 },
    { answer: "Leonard", points: 1 },
    { answer: "Liam", points: 1 },
    { answer: "Logan", points: 1 },
    { answer: "Louis", points: 1 },
    { answer: "Lucas", points: 1 },
    { answer: "Luke", points: 1 },
    { answer: "Lamar", points: 2 },
    { answer: "Lance", points: 2 },
    { answer: "Landon", points: 2 },
    { answer: "Lenny", points: 2 },
    { answer: "Leon", points: 2 },
    { answer: "Leroy", points: 2 },
    { answer: "Lester", points: 2 },
    { answer: "Levi", points: 2 },
    { answer: "Lewis", points: 2 },
    { answer: "Lincoln", points: 2 },
    { answer: "Lionel", points: 2 },
    { answer: "Lloyd", points: 2 },
    { answer: "Lonnie", points: 2 },
    { answer: "Lorenzo", points: 2 },
    { answer: "Luca", points: 2 },
    { answer: "Luis", points: 2 },
    { answer: "Luther", points: 2 },
    { answer: "Lachlan", points: 3 },
    { answer: "Landers", points: 3 },
    { answer: "Landry", points: 3 },
    { answer: "Langston", points: 3 },
    { answer: "Lark", points: 3 },
    { answer: "Lars", points: 3 },
    { answer: "Lathan", points: 3 },
    { answer: "Laurence", points: 3 },
    { answer: "Laurent", points: 3 },
    { answer: "Lawson", points: 3 },
    { answer: "Layton", points: 3 },
    { answer: "Lazaro", points: 3 },
    { answer: "Lazarus", points: 3 },
    { answer: "Leandro", points: 3 },
    { answer: "Ledger", points: 3 },
    { answer: "Leif", points: 3 },
    { answer: "Leighton", points: 3 },
    { answer: "Leland", points: 3 },
    { answer: "Lennard", points: 3 },
    { answer: "Lennon", points: 3 },
    { answer: "Lennox", points: 3 },
    { answer: "Leopold", points: 3 },
    { answer: "Leron", points: 3 },
    { answer: "Leslie", points: 3 },
    { answer: "Lev", points: 3 },
    { answer: "Levin", points: 3 },
    { answer: "Lindell", points: 3 },
    { answer: "Lindsey", points: 3 },
    { answer: "Linus", points: 3 },
    { answer: "Lisandro", points: 3 },
    { answer: "Llewellyn", points: 3 },
    { answer: "Loman", points: 3 },
    { answer: "London", points: 3 },
    { answer: "Lonzo", points: 3 },
    { answer: "Lorcan", points: 3 },
    { answer: "Lorenz", points: 3 },
    { answer: "Lorne", points: 3 },
    { answer: "Louie", points: 3 },
    { answer: "Lowell", points: 3 },
    { answer: "Loyal", points: 3 },
    { answer: "Lucian", points: 3 },
    { answer: "Luciano", points: 3 },
    { answer: "Lucio", points: 3 },
    { answer: "Ludo", points: 3 },
    { answer: "Luka", points: 3 },
    { answer: "Lyle", points: 3 },
    { answer: "Lyndon", points: 3 },
    { answer: "Lyric", points: 3 }
  ],

  "Girl Names Starting with L": [
    { answer: "Laura", points: 1 },
    { answer: "Lauren", points: 1 },
    { answer: "Leah", points: 1 },
    { answer: "Leslie", points: 1 },
    { answer: "Lillian", points: 1 },
    { answer: "Lily", points: 1 },
    { answer: "Linda", points: 1 },
    { answer: "Lindsay", points: 1 },
    { answer: "Lisa", points: 1 },
    { answer: "Lori", points: 1 },
    { answer: "Lucy", points: 1 },
    { answer: "Luna", points: 1 },
    { answer: "Lydia", points: 1 },
    { answer: "Lacey", points: 2 },
    { answer: "Lara", points: 2 },
    { answer: "Layla", points: 2 },
    { answer: "Leila", points: 2 },
    { answer: "Leilani", points: 2 },
    { answer: "Lena", points: 2 },
    { answer: "Lexi", points: 2 },
    { answer: "Lila", points: 2 },
    { answer: "Liliana", points: 2 },
    { answer: "Lola", points: 2 },
    { answer: "Loretta", points: 2 },
    { answer: "Lorraine", points: 2 },
    { answer: "Louise", points: 2 },
    { answer: "Lucia", points: 2 },
    { answer: "Lucille", points: 2 },
    { answer: "Lainey", points: 3 },
    { answer: "Laken", points: 3 },
    { answer: "Landry", points: 3 },
    { answer: "Laney", points: 3 },
    { answer: "Larissa", points: 3 },
    { answer: "Lark", points: 3 },
    { answer: "Laurel", points: 3 },
    { answer: "Laverne", points: 3 },
    { answer: "Lavinia", points: 3 },
    { answer: "Leanne", points: 3 },
    { answer: "Lennon", points: 3 },
    { answer: "Lenora", points: 3 },
    { answer: "Lenore", points: 3 },
    { answer: "Leona", points: 3 },
    { answer: "Leticia", points: 3 },
    { answer: "Lexie", points: 3 },
    { answer: "Liana", points: 3 },
    { answer: "Libby", points: 3 },
    { answer: "Liberty", points: 3 },
    { answer: "Lidia", points: 3 },
    { answer: "Liesel", points: 3 },
    { answer: "Lilith", points: 3 },
    { answer: "Lillie", points: 3 },
    { answer: "Lilyanna", points: 3 },
    { answer: "Lina", points: 3 },
    { answer: "Linnea", points: 3 },
    { answer: "Lisbeth", points: 3 },
    { answer: "Lisette", points: 3 },
    { answer: "Livia", points: 3 },
    { answer: "Liza", points: 3 },
    { answer: "Lizbeth", points: 3 },
    { answer: "Lorelei", points: 3 },
    { answer: "Lorena", points: 3 },
    { answer: "Lottie", points: 3 },
    { answer: "Lotus", points: 3 },
    { answer: "Louisa", points: 3 },
    { answer: "Lourdes", points: 3 },
    { answer: "Luciana", points: 3 },
    { answer: "Lucinda", points: 3 },
    { answer: "Luella", points: 3 },
    { answer: "Luisa", points: 3 },
    { answer: "Lupita", points: 3 },
    { answer: "Lux", points: 3 },
    { answer: "Luz", points: 3 },
    { answer: "Lynnette", points: 3 },
    { answer: "Lyra", points: 3 },
    { answer: "Lyric", points: 3 }
  ],

  "Boy Names Starting with S": [
    { answer: "Sam", points: 1 },
    { answer: "Samuel", points: 1 },
    { answer: "Scott", points: 1 },
    { answer: "Sean", points: 1 },
    { answer: "Shane", points: 1 },
    { answer: "Shawn", points: 1 },
    { answer: "Spencer", points: 1 },
    { answer: "Stanley", points: 1 },
    { answer: "Stephen", points: 1 },
    { answer: "Steven", points: 1 },
    { answer: "Sammy", points: 2 },
    { answer: "Santiago", points: 2 },
    { answer: "Saul", points: 2 },
    { answer: "Sawyer", points: 2 },
    { answer: "Sebastian", points: 2 },
    { answer: "Sergio", points: 2 },
    { answer: "Seth", points: 2 },
    { answer: "Sheldon", points: 2 },
    { answer: "Sherman", points: 2 },
    { answer: "Sidney", points: 2 },
    { answer: "Simon", points: 2 },
    { answer: "Skyler", points: 2 },
    { answer: "Solomon", points: 2 },
    { answer: "Steve", points: 2 },
    { answer: "Stuart", points: 2 },
    { answer: "Sabastian", points: 3 },
    { answer: "Sage", points: 3 },
    { answer: "Sailor", points: 3 },
    { answer: "Salvador", points: 3 },
    { answer: "Salvatore", points: 3 },
    { answer: "Samson", points: 3 },
    { answer: "Samwell", points: 3 },
    { answer: "Sanjay", points: 3 },
    { answer: "Santana", points: 3 },
    { answer: "Santino", points: 3 },
    { answer: "Santos", points: 3 },
    { answer: "Saxon", points: 3 },
    { answer: "Scotty", points: 3 },
    { answer: "Seamus", points: 3 },
    { answer: "Severin", points: 3 },
    { answer: "Severino", points: 3 },
    { answer: "Severus", points: 3 },
    { answer: "Seymour", points: 3 },
    { answer: "Shay", points: 3 },
    { answer: "Shelton", points: 3 },
    { answer: "Shepherd", points: 3 },
    { answer: "Shiloh", points: 3 },
    { answer: "Silas", points: 3 },
    { answer: "Silvano", points: 3 },
    { answer: "Silvio", points: 3 },
    { answer: "Simeon", points: 3 },
    { answer: "Sinclair", points: 3 },
    { answer: "Skylar", points: 3 },
    { answer: "Slade", points: 3 },
    { answer: "Slater", points: 3 },
    { answer: "Sonny", points: 3 },
    { answer: "Soren", points: 3 },
    { answer: "Sorrell", points: 3 },
    { answer: "Stanton", points: 3 },
    { answer: "Stefan", points: 3 },
    { answer: "Stefano", points: 3 },
    { answer: "Stellan", points: 3 },
    { answer: "Stellano", points: 3 },
    { answer: "Sterling", points: 3 },
    { answer: "Stetson", points: 3 },
    { answer: "Stirling", points: 3 },
    { answer: "Stockton", points: 3 },
    { answer: "Stone", points: 3 },
    { answer: "Storm", points: 3 },
    { answer: "Sullivan", points: 3 },
    { answer: "Sully", points: 3 },
    { answer: "Sunny", points: 3 },
    { answer: "Sutton", points: 3 },
    { answer: "Sylvester", points: 3 }
  ],

  "Girl Names Starting with S": [
    { answer: "Sabrina", points: 1 },
    { answer: "Samantha", points: 1 },
    { answer: "Sandra", points: 1 },
    { answer: "Sara", points: 1 },
    { answer: "Sarah", points: 1 },
    { answer: "Shannon", points: 1 },
    { answer: "Shelby", points: 1 },
    { answer: "Shirley", points: 1 },
    { answer: "Sophia", points: 1 },
    { answer: "Stephanie", points: 1 },
    { answer: "Susan", points: 1 },
    { answer: "Sadie", points: 2 },
    { answer: "Sasha", points: 2 },
    { answer: "Savannah", points: 2 },
    { answer: "Scarlett", points: 2 },
    { answer: "Selena", points: 2 },
    { answer: "Serena", points: 2 },
    { answer: "Sienna", points: 2 },
    { answer: "Sierra", points: 2 },
    { answer: "Simone", points: 2 },
    { answer: "Skylar", points: 2 },
    { answer: "Sofia", points: 2 },
    { answer: "Sonia", points: 2 },
    { answer: "Stacy", points: 2 },
    { answer: "Stella", points: 2 },
    { answer: "Summer", points: 2 },
    { answer: "Sydney", points: 2 },
    { answer: "Sylvia", points: 2 },
    { answer: "Sage", points: 3 },
    { answer: "Sahara", points: 3 },
    { answer: "Salem", points: 3 },
    { answer: "Salma", points: 3 },
    { answer: "Salome", points: 3 },
    { answer: "Samara", points: 3 },
    { answer: "Samira", points: 3 },
    { answer: "Saoirse", points: 3 },
    { answer: "Sapphire", points: 3 },
    { answer: "Sarai", points: 3 },
    { answer: "Sariah", points: 3 },
    { answer: "Saylor", points: 3 },
    { answer: "Scout", points: 3 },
    { answer: "Selene", points: 3 },
    { answer: "Selma", points: 3 },
    { answer: "Seraphina", points: 3 },
    { answer: "Sevyn", points: 3 },
    { answer: "Shakira", points: 3 },
    { answer: "Shania", points: 3 },
    { answer: "Shay", points: 3 },
    { answer: "Shayla", points: 3 },
    { answer: "Shayna", points: 3 },
    { answer: "Shea", points: 3 },
    { answer: "Sheila", points: 3 },
    { answer: "Sherry", points: 3 },
    { answer: "Sheryl", points: 3 },
    { answer: "Shiloh", points: 3 },
    { answer: "Siena", points: 3 },
    { answer: "Sigrid", points: 3 },
    { answer: "Skye", points: 3 },
    { answer: "Sloane", points: 3 },
    { answer: "Socorro", points: 3 },
    { answer: "Solana", points: 3 },
    { answer: "Solange", points: 3 },
    { answer: "Soleil", points: 3 },
    { answer: "Soraya", points: 3 },
    { answer: "Star", points: 3 },
    { answer: "Starla", points: 3 },
    { answer: "Stevie", points: 3 },
    { answer: "Storm", points: 3 },
    { answer: "Sunny", points: 3 },
    { answer: "Susana", points: 3 },
    { answer: "Susannah", points: 3 },
    { answer: "Sutton", points: 3 },
    { answer: "Suzette", points: 3 },
    { answer: "Svetlana", points: 3 },
    { answer: "Sybil", points: 3 },
    { answer: "Sylvie", points: 3 }
  ],

  "US Presidents": [
    // Common (1 point)
    { answer: "George Washington", points: 1 },
    { answer: "Abraham Lincoln", points: 1, aliases: ["Abe Lincoln", "Abe", "Honest Abe"] },
    { answer: "Barack Obama", points: 1 },
    { answer: "Donald Trump", points: 1 },
    { answer: "Joe Biden", points: 1, aliases: ["Biden"] },
    { answer: "John F. Kennedy", points: 1, aliases: ["JFK", "Kennedy"] },
    { answer: "Thomas Jefferson", points: 1 },
    { answer: "Theodore Roosevelt", points: 1, aliases: ["Teddy Roosevelt", "Teddy"] },
    // Moderate (2 points)
    { answer: "Franklin Roosevelt", points: 2, aliases: ["FDR", "Franklin D. Roosevelt"] },
    { answer: "Ronald Reagan", points: 2 },
    { answer: "Bill Clinton", points: 2, aliases: ["William Clinton"] },
    { answer: "George H.W. Bush", points: 2, aliases: ["George Bush Senior", "Bush Senior", "H.W. Bush"] },
    { answer: "George W. Bush", points: 2, aliases: ["Dubya", "W Bush", "Bush Junior", "George Bush Junior"] },
    { answer: "Richard Nixon", points: 2, aliases: ["Nixon", "Dick Nixon"] },
    { answer: "Jimmy Carter", points: 2, aliases: ["James Carter"] },
    { answer: "Andrew Jackson", points: 2 },
    { answer: "Dwight Eisenhower", points: 2, aliases: ["Ike", "Dwight D. Eisenhower"] },
    { answer: "Harry Truman", points: 2, aliases: ["Harry S. Truman"] },
    { answer: "John Adams", points: 2 },
    { answer: "James Madison", points: 2 },
    { answer: "Ulysses S. Grant", points: 2, aliases: ["Ulysses Grant", "U.S. Grant"] },
    { answer: "Woodrow Wilson", points: 2 },
    { answer: "Lyndon B. Johnson", points: 2, aliases: ["LBJ", "Lyndon Johnson"] },
    // Niche (3 points)
    { answer: "James Monroe", points: 3 },
    { answer: "John Quincy Adams", points: 3, aliases: ["JQA"] },
    { answer: "Martin Van Buren", points: 3 },
    { answer: "William Henry Harrison", points: 3 },
    { answer: "John Tyler", points: 3 },
    { answer: "James K. Polk", points: 3, aliases: ["James Polk"] },
    { answer: "Zachary Taylor", points: 3 },
    { answer: "Millard Fillmore", points: 3 },
    { answer: "Franklin Pierce", points: 3 },
    { answer: "James Buchanan", points: 3 },
    { answer: "Andrew Johnson", points: 3 },
    { answer: "Rutherford B. Hayes", points: 3, aliases: ["Rutherford Hayes"] },
    { answer: "James Garfield", points: 3 },
    { answer: "Chester Arthur", points: 3, aliases: ["Chester A. Arthur"] },
    { answer: "Grover Cleveland", points: 3 },
    { answer: "Benjamin Harrison", points: 3 },
    { answer: "William McKinley", points: 3 },
    { answer: "William Howard Taft", points: 3 },
    { answer: "Warren G. Harding", points: 3, aliases: ["Warren Harding"] },
    { answer: "Calvin Coolidge", points: 3 },
    { answer: "Herbert Hoover", points: 3 },
    { answer: "Gerald Ford", points: 3 }
  ],

  "Super Smash Bros Characters": [
    // Common (1 point) - the most iconic fighters, anyone who's touched Smash knows these
    { answer: "Mario", points: 1 },
    { answer: "Luigi", points: 1 },
    { answer: "Peach", points: 1, aliases: ["Princess Peach"] },
    { answer: "Bowser", points: 1 },
    { answer: "Yoshi", points: 1 },
    { answer: "Donkey Kong", points: 1, aliases: ["DK"] },
    { answer: "Link", points: 1 },
    { answer: "Zelda", points: 1, aliases: ["Princess Zelda"] },
    { answer: "Pikachu", points: 1 },
    { answer: "Kirby", points: 1 },
    { answer: "Samus", points: 1, aliases: ["Samus Aran"] },
    { answer: "Fox", points: 1, aliases: ["Fox McCloud"] },
    // Moderate (2 points) - well-known to casual Smash players
    { answer: "Captain Falcon", points: 2, aliases: ["Falcon"] },
    { answer: "Ness", points: 2 },
    { answer: "Jigglypuff", points: 2, aliases: ["Jiggly"] },
    { answer: "Ganondorf", points: 2, aliases: ["Ganon"] },
    { answer: "Falco", points: 2, aliases: ["Falco Lombardi"] },
    { answer: "Marth", points: 2 },
    { answer: "Sheik", points: 2 },
    { answer: "Mewtwo", points: 2 },
    { answer: "Mr. Game & Watch", points: 2, aliases: ["Game and Watch", "Mr Game and Watch"] },
    { answer: "Meta Knight", points: 2 },
    { answer: "Pit", points: 2 },
    { answer: "Wario", points: 2 },
    { answer: "Snake", points: 2, aliases: ["Solid Snake"] },
    { answer: "Sonic", points: 2, aliases: ["Sonic the Hedgehog"] },
    { answer: "King Dedede", points: 2, aliases: ["Dedede"] },
    { answer: "Diddy Kong", points: 2 },
    { answer: "Charizard", points: 2 },
    { answer: "Ice Climbers", points: 2, aliases: ["Popo", "Nana"] },
    { answer: "Wolf", points: 2, aliases: ["Wolf O'Donnell"] },
    { answer: "Toon Link", points: 2 },
    { answer: "Lucario", points: 2 },
    { answer: "R.O.B.", points: 2 },
    { answer: "Pac-Man", points: 2, aliases: ["Pacman"] },
    { answer: "Mega Man", points: 2, aliases: ["Megaman"] },
    { answer: "Cloud", points: 2, aliases: ["Cloud Strife"] },
    { answer: "Little Mac", points: 2 },
    { answer: "Villager", points: 2 },
    { answer: "Inkling", points: 2 },
    // Niche (3 points) - DLC fighters, echo fighters, deep roster knowledge
    { answer: "Roy", points: 3 },
    { answer: "Dr. Mario", points: 3 },
    { answer: "Young Link", points: 3 },
    { answer: "Pichu", points: 3 },
    { answer: "Ike", points: 3 },
    { answer: "Lucas", points: 3 },
    { answer: "Olimar", points: 3, aliases: ["Captain Olimar"] },
    { answer: "Lucina", points: 3 },
    { answer: "Robin", points: 3 },
    { answer: "Shulk", points: 3 },
    { answer: "Bowser Jr.", points: 3, aliases: ["Bowser Junior"] },
    { answer: "Duck Hunt", points: 3, aliases: ["Duck Hunt Duo"] },
    { answer: "Rosalina & Luma", points: 3, aliases: ["Rosalina", "Rosalina and Luma"] },
    { answer: "Greninja", points: 3 },
    { answer: "Palutena", points: 3 },
    { answer: "Dark Pit", points: 3 },
    { answer: "Wii Fit Trainer", points: 3 },
    { answer: "Ryu", points: 3 },
    { answer: "Corrin", points: 3 },
    { answer: "Bayonetta", points: 3 },
    { answer: "Ridley", points: 3 },
    { answer: "Simon", points: 3, aliases: ["Simon Belmont"] },
    { answer: "Richter", points: 3, aliases: ["Richter Belmont"] },
    { answer: "King K. Rool", points: 3, aliases: ["K. Rool", "King K Rool"] },
    { answer: "Isabelle", points: 3 },
    { answer: "Incineroar", points: 3 },
    { answer: "Ken", points: 3, aliases: ["Ken Masters"] },
    { answer: "Daisy", points: 3, aliases: ["Princess Daisy"] },
    { answer: "Dark Samus", points: 3 },
    { answer: "Chrom", points: 3 },
    { answer: "Zero Suit Samus", points: 3, aliases: ["ZSS", "Zero Suit"] },
    { answer: "Ivysaur", points: 3 },
    { answer: "Squirtle", points: 3 },
    { answer: "Joker", points: 3 },
    { answer: "Hero", points: 3 },
    { answer: "Banjo & Kazooie", points: 3, aliases: ["Banjo", "Banjo and Kazooie", "Banjo Kazooie"] },
    { answer: "Terry", points: 3, aliases: ["Terry Bogard"] },
    { answer: "Byleth", points: 3 },
    { answer: "Min Min", points: 3 },
    { answer: "Steve", points: 3, aliases: ["Minecraft Steve"] },
    { answer: "Sephiroth", points: 3 },
    { answer: "Pyra", points: 3 },
    { answer: "Mythra", points: 3 },
    { answer: "Kazuya", points: 3, aliases: ["Kazuya Mishima"] },
    { answer: "Sora", points: 3 },
    { answer: "Piranha Plant", points: 3 },
    { answer: "Mii Brawler", points: 3 },
    { answer: "Mii Gunner", points: 3 },
    { answer: "Mii Swordfighter", points: 3, aliases: ["Mii Sword Fighter"] }
  ]
};
